apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubemaster
  region: us-east-1

# nodeGroups:
#   - name: windows-ng
#     amiFamily: WindowsServer2019CoreContainer
#     desiredCapacity: 1
#     instanceType: t2.small
#     volumeSize: 50
#     volumeType: gp2
managedNodeGroups:
  - name: linux-ng
    desiredCapacity: 1
    instanceType: t2.small
    volumeSize: 40
    volumeType: gp2