#Create a file named vpc-resource-controller-configmap.yaml with the following contents.
apiVersion: v1
kind: ConfigMap
metadata:
  name: amazon-vpc-cni
  namespace: kube-system
data:
  enable-windows-ipam: "true"