apiVersion: apps/v1
kind: Deployment 
metadata:
  name: usermgmt-microservice
  labels:
    app: usermgmt-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-restapp
  template:  
    metadata:
      labels: 
        app: usermgmt-restapp
    spec:
      serviceAccountName: wordpressmysql
      containers:
        - name: usermgmt-restapp
          image: stacksimplify/kube-usermanagement-microservice:1.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets"
            readOnly: true  
          ports: 
            - containerPort: 8095
          resources:
           limits:
            memory: 500Mi
            cpu: 500m
           requests:
            memory: 300Mi
            cpu: 200m        
          env:
            - name: DB_HOSTNAME
              value: mysql            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: usermgmt            
            - name: DB_USERNAME
              value: dbadmin       # RDS DB Username is dbadmin     
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlwordpress
                  key: springbootsecret           
          livenessProbe:
            exec:
              command: 
                - /bin/sh
                - -c 
                - nc -z localhost 8095
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /usermgmt/health-status
              port: 8095
            initialDelaySeconds: 60
            periodSeconds: 1
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: mysqlwordpressdeploy   