apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kubemaster
  region: us-east-1
  version: "1.25"
iam:
  withOIDC: true
vpc:
  id: "vpc-09b89dd90231cfdfa"
  subnets:
    public:
      us-east-1a:
          id: "subnet-05cd1f135db8cdfa1"
      us-west-1b:
          id: "subnet-0e941cafe46d2ee0a"