apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: basic-cluster
  region: us-east-1
  version: "1.25"
iam:
  withOIDC: true
vpc:
  id: "vpc-09b89dd90231cfdfa"
  subnets:
    public:
      us-east-1a:
          id: "subnet-05cd1f135db8cdfa1"
      us-west-1b:
          id: "subnet-0e941cafe46d2ee0a"
managedNodeGroups:
- amiFamily: AmazonLinux2
  name: linuxworker
  desiredCapacity: 1
  instanceType: t3.small
  volumeType: gp2
  volumeSize: 20
  labels: { role: workers }
  iam:
    withAddonPolicies:
      albIngress: true
      appMesh: true
      autoScaler: true
      awsLoadBalancerController: true
      certManager: false
      cloudWatch: true
      ebs: true
      externalDNS: true
      imageBuilder: true
  ssh:
    enableSsm: true