apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysqlwordpressdeploy
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: "DBSecret_eksworkshop"
        objectType: "secretsmanager"
        jmesPath:
          - path: password 
            objectAlias: dbpassword
          - path: masterpassword
            objectAlias: masterpasswordalias
  # the path set inside jmesPath is same as the secret name declared in secretmanager
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:                
    - secretName: mysqlwordpress
      type: Opaque
      data:
        #- objectName: <objectName> or <objectAlias>
        # the key will be used in deployment secret file
        - objectName: dbpassword
          key: mysqlsecret
        - objectName: masterpasswordalias
          key: springbootsecret